config/routes.rb
Rails.application.routes.draw do
  root 'songs#index'
  resources :songs, only: [:index] do
    resources :favorites
  end

  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :favorites
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def new
    @favorite = Favorite.new
  end

  def create
    @favorite = Favorite.new(favorite_params)
    if @favorite.save
      render 'songs#index'
    end
  end

  private

  def favorite_params
    params.require(:favorite)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavoriteSongsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <% if !current_user %>
      <button class="button"> <%= link_to 'Log in', login_path %> </button>
      <button class="button"> <%= link_to 'Register', new_user_path %> </button>
    <% else %>
       <%= link_to "#{current_user.name}", user_path(current_user) %> <button class="button"> <%= link_to 'Logout', logout_path %> </button>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h1>That's My Song!</h1>

<div class="song-list">
  <% @songs.each do |song| %>
    <%= form_tag("favorites#create") do %>
      <p><%= hidden_field_tag :user_id, :value => current_user.id %></p>
      <p><%= hidden_field_tag :song_id, :value => song.id %></p>
      <p><%= submit_tag "Favorite" %></p>
    <% end %>
    <h4 class="song-title"><%= song.title %></h4>
    <p class="song-artist"><%= song.artist %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<h2>Sign up here!!!</h2>

<%= form_for(@user) do |f|  %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>
  <p>
  <%= f.label :email %>
  <%= f.email_field :email %>
   </p>
   <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
   </p>
   <p>
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation %>
   </p>
   <p>
    <%= f.submit "Submit" %>
   </p>
<% end %>